import { FaClipboard, FaSun, FaBook } from "react-icons/fa";
import {BiCricketBall, BiSolidCricketBall} from 'react-icons/bi'
import { Project } from "./types/project";

export const Projects: Project[] = [
    {
        id: "1",
        title: "Gnews API",
        description: "A simple API to get news from Google News. Functionality to save favourites when signed in via Google.",
        status: false,
        techs: ["redux", "react", "firebase", 'API'],
        link: '',
        image: FaSun,
        team: false,
        docuemntation: '',
        code: 'https://github.com/luiHoll97/redux-gnews-api',
        linksAvailable: true,
    },
    {
        id: "4",
        title: "Portfolio",
        description: "A simple portfolio website to showcase my projects. The page is now inactive as I have moved to a new portfolio site.",
        status: true,
        techs: ["react", "javascript", "CSS"],
        link:'https://lui-holliday.netlify.app',
        image: FaClipboard,
        team: false,
        docuemntation: '',
        code: 'https://github.com/luiHoll97/lui-portfolio',
        linksAvailable: true,
    },
      {
        id: '6',
        title: "Resource Sharer",
        description: 'A simple resource sharing app that allows users to share resources with each other.',
        image: FaBook,
        techs: ["react", "express", "PostgreSQL", 'node'],
        link: "https://c5c2-study-resources.netlify.app",
        status: true,
        team: true,
        docuemntation: '',
        code: '',
        linksAvailable: true,
      },
      {
        id: '7',
        title: "Cricket Scoreboard",
        description: 'A Cricket Scoring app. Create and save matches, teams and players specific to the users gmail ID',
        image: BiCricketBall,
        techs: ["react", 'chakra-ui', "Firebase"],
        link: "",
        status: false,
        team: false,
        docuemntation: '',
        code: 'https://github.com/luiHoll97/cricket-scorer',
        linksAvailable: true,
      },
      {
        id: '8',
        title: "redux scorer",
        description: 'A simple cricket scoreboard app using redux. I used this to see how I could use redux to manage state for my other app.',
        image: BiSolidCricketBall,
        techs: ["react", 'redux'],
        link: "https://redux-scorer.netlify.app",
        status: true,
        team: false,
        docuemntation: '',
        code: 'https://github.com/luiHoll97/redux-scorer',
        linksAvailable: true,
      }

]